# Generated by Django 4.1.7 on 2023-04-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('followerId', models.IntegerField()),
                ('followedId', models.IntegerField()),
                ('blocked', models.BooleanField(default=False)),
                ('createdDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
